In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

TODO: Agregado por tipo de instancia, máximo y media (a lo mejor algo más) de sesiones, usuarios, duración, etc.

In [3]:
def calculate_stats(file):
    viewer_count_array = []
    viewer_count = 0
    viewer_count_session = {}
    timestamps = []
    timestamps_sessions = [0]
    sessions = [0]

    with open(file, 'r') as f:
        # Skip header line
        next(f)
        for line in f:
            parts = line.strip().split(',')
            if len(parts) < 4:
                continue

            event = int(parts[0])
            id_val = parts[1]
            timestamp = float(parts[2])
            repeat = int(parts[3])

            if event == 0:  # Session start
                session = f"{id_val}-{repeat}"
                viewer_count_session[session] = {
                    "viewer_count": 0,
                    "viewer_count_array": [0],
                    "timestamps": [timestamp]
                }
                sessions.append(sessions[-1] + 1)
                timestamps_sessions.append(timestamp)

            elif event == 2:  # Session end
                session = f"{id_val}-{repeat}"
                if session in viewer_count_session:
                    viewer_count -= viewer_count_session[session]["viewer_count"]
                sessions.append(sessions[-1] - 1)
                timestamps_sessions.append(timestamp)

            elif event in [1, 3]:  # User join/leave
                session = f"{'-'.join(id_val.split('-')[:-1])}-{repeat}"
                if session in viewer_count_session:
                    session_data = viewer_count_session[session]
                    
                    if event == 1:  # User join
                        session_data["viewer_count"] += 1
                        viewer_count += 1
                    else:  # User leave
                        session_data["viewer_count"] -= 1
                        viewer_count -= 1

                    session_data["viewer_count_array"].append(session_data["viewer_count"])
                    session_data["timestamps"].append(timestamp)

            viewer_count_array.append(viewer_count)
            timestamps.append(timestamp)
    
    return viewer_count_array, timestamps, viewer_count_session, timestamps_sessions, sessions

def get_files(size="small"):
    files = []
    for root, _, system_filenames in os.walk(f"instances/instances-{size}"):
        for filename in system_filenames:
            if filename.endswith(".csv"):
                files.append(os.path.join(root, filename))
    return files

small = {
    "Instance": [],
    "Max users": [],
    "Average users": [],
    "Median users": [],
    "Standard deviation users": [],
    "Max sessions": [],
    "Average sessions": [],
    "Median sessions": [],
    "Standard deviation sessions": [],
    "Max duration (s)": []
}

for file in get_files("small"):
    filename = os.path.basename(file)
    small["Instance"].append(filename)
    viewer_count_array, timestamps, viewer_count_session, timestamps_sessions, sessions = calculate_stats(file)
    max_duration = max(timestamps_sessions)
    small["Max duration (s)"].append(max_duration)
    max_users = max(viewer_count_array)
    small["Max users"].append(max_users)
    small["Average users"].append(np.mean(viewer_count_array))
    small["Median users"].append(np.median(viewer_count_array))
    small["Standard deviation users"].append(np.std(viewer_count_array))
    small["Max sessions"].append(max(sessions))
    small["Average sessions"].append(np.mean(sessions))
    small["Median sessions"].append(np.median(sessions))
    small["Standard deviation sessions"].append(np.std(sessions))

small_df = pd.DataFrame(small)
display(small_df)

,Instance,Max users,Average users,Median users,Standard deviation users,Max sessions,Average sessions,Median sessions,Standard deviation sessions,Max duration (s)
0,instance-small-0.csv,9883,4804.250261,4663.0,1716.668818,6,3.714286,4.0,1.267548,52119.199023
1,instance-small-1.csv,14783,8588.869260,9238.0,2884.438421,9,5.876543,6.0,1.907637,38236.748303
2,instance-small-10.csv,11928,7324.204893,7511.0,2052.714150,9,6.117647,6.0,1.868700,38082.684503
3,instance-small-11.csv,11677,6300.604304,6153.0,1924.185251,8,5.120482,5.0,1.689069,38909.047135
4,instance-small-12.csv,14045,8670.655795,9142.0,2940.301587,8,5.901408,6.0,1.907398,38869.659051
5,instance-small-13.csv,7157,3772.083911,3675.0,1471.160305,6,3.884058,4.0,1.324641,50635.961188
6,instance-small-14.csv,5384,2909.616430,2867.0,1164.176389,5,2.538462,3.0,1.194993,40901.732088
7,instance-small-15.csv,7143,3404.656476,3536.0,1332.365406,6,3.267327,3.0,1.209624,102873.054401
8,instance-small-16.csv,9269,5002.766150,5196.0,1960.898537,6,3.632653,4.0,1.409789,29409.822205
9,instance-small-17.csv,12298,7342.198184,7324.0,2113.587194,10,6.422360,7.0,1.739707,115431.627754
10,instance-small-18.csv,16915,10871.169147,10500.0,3116.905926,8,5.373333,6.0,1.726448,29133.099030
11,instance-small-19.csv,4000,2408.486082,2481.0,835.359316,4,2.333333,2.0,0.942809,35071.086803
12,instance-small-2.csv,7085,3948.299239,4036.0,1479.783907,6,3.755102,4.0,1.317552,40325.848828
13,instance-small-20.csv,7233,3508.381028,3366.0,1512.730747,6,3.415385,4.0,1.148810,53276.483989
14,instance-small-21.csv,12672,6941.374174,7005.0,2366.423394,8,5.764706,6.0,1.806179,38020.143777
15,instance-small-22.csv,8647,3445.789508,3383.0,1425.829034,4,2.448980,3.0,0.970193,45744.945718
16,instance-small-23.csv,5840,3094.158128,3093.0,1120.205158,6,3.135593,3.0,1.227615,46510.911598
17,instance-small-24.csv,9392,5603.633726,5728.0,1526.981177,8,5.612903,6.0,1.633206,45312.455854
18,instance-small-25.csv,9972,6501.576779,6255.0,1907.333243,10,7.131868,8.0,2.128864,32933.446785
19,instance-small-26.csv,9558,4416.662125,4308.0,1775.760481,7,4.356589,4.0,1.218707,100319.483108
20,instance-small-27.csv,8836,4531.239157,4266.0,1525.872308,5,3.639344,4.0,1.215107,46239.554755
21,instance-small-28.csv,7607,3972.822641,3863.0,1526.735716,4,2.487805,3.0,1.015056,41126.250104
22,instance-small-29.csv,8108,3310.885406,2985.0,1633.561220,6,3.362832,3.0,1.137160,119870.799899
23,instance-small-3.csv,8878,5794.308963,5818.0,1476.479396,7,4.894118,5.0,1.541760,48891.546588
24,instance-small-30.csv,12418,6078.611857,5892.0,2349.572637,9,5.917526,6.0,1.837020,39339.209643
25,instance-small-31.csv,6052,2832.893038,2867.0,1307.134111,5,2.367347,2.0,1.119291,53992.279104
26,instance-small-32.csv,9905,4801.015139,4928.0,2387.802648,5,2.702703,3.0,1.227277,32452.918760
27,instance-small-33.csv,10393,5531.446421,5320.0,1789.638688,8,5.303030,5.0,1.648106,50933.480937
28,instance-small-34.csv,10660,5574.792919,5931.0,2254.283731,7,4.153846,4.0,1.541535,50401.116313
29,instance-small-35.csv,9578,5026.411222,5207.0,1600.035731,8,5.253165,6.0,1.679876,38572.680873
30,instance-small-36.csv,10916,6784.488296,7092.0,2110.212996,8,5.139785,5.0,1.583459,52014.189020
31,instance-small-37.csv,7121,2662.356056,2374.0,1460.759841,5,2.145038,2.0,0.997111,358539.498306
32,instance-small-38.csv,9860,3992.055534,3839.0,2194.371702,4,1.981818,2.0,0.999835,90904.862166
33,instance-small-39.csv,9375,3752.619653,3442.0,1977.106122,4,2.486486,3.0,1.055785,40915.338129
34,instance-small-4.csv,10888,6563.893443,6751.0,2164.716847,9,5.835443,6.0,1.858476,35188.693541
35,instance-small-5.csv,8152,4236.697370,4331.0,1602.334147,5,3.224490,3.0,1.129661,42711.119997
36,instance-small-6.csv,12015,6190.723016,6073.0,2696.181803,7,4.522388,5.0,1.499833,39686.515368
37,instance-small-7.csv,14654,8996.286325,9095.0,2744.442161,9,6.325301,7.0,1.964188,31437.677303
38,instance-small-8.csv,6370,3856.768247,3876.0,1020.457381,5,2.844444,3.0,1.094543,47909.235258
39,instance-small-9.csv,6357,2438.267743,2269.0,1127.914958,5,2.760000,3.0,1.030728,357231.476144

In [4]:
medium = {
    "Instance": [],
    "Max users": [],
    "Average users": [],
    "Median users": [],
    "Standard deviation users": [],
    "Max sessions": [],
    "Average sessions": [],
    "Median sessions": [],
    "Standard deviation sessions": [],
    "Max duration (s)": []
}

for file in get_files("medium"):
    filename = os.path.basename(file)
    medium["Instance"].append(filename)
    viewer_count_array, timestamps, viewer_count_session, timestamps_sessions, sessions = calculate_stats(file)
    max_duration = max(timestamps_sessions)
    medium["Max duration (s)"].append(max_duration)
    max_users = max(viewer_count_array)
    medium["Max users"].append(max_users)
    medium["Average users"].append(np.mean(viewer_count_array))
    medium["Median users"].append(np.median(viewer_count_array))
    medium["Standard deviation users"].append(np.std(viewer_count_array))
    medium["Max sessions"].append(max(sessions))
    medium["Average sessions"].append(np.mean(sessions))
    medium["Median sessions"].append(np.median(sessions))
    medium["Standard deviation sessions"].append(np.std(sessions))

medium_df = pd.DataFrame(medium)
display(medium_df)

,Instance,Max users,Average users,Median users,Standard deviation users,Max sessions,Average sessions,Median sessions,Standard deviation sessions,Max duration (s)
0,instance-medium-0.csv,92960,62844.892242,63152.0,12613.630580,35,29.861968,31.0,5.598278,83323.146624
1,instance-medium-1.csv,83809,60373.939465,61519.0,12515.550610,30,25.278912,27.0,5.623625,52978.467108
2,instance-medium-10.csv,135944,102293.995260,102986.0,15226.166585,50,43.383133,45.0,7.157452,111366.882748
3,instance-medium-11.csv,69811,49643.463084,51184.0,11389.116060,25,20.484211,22.0,5.129611,44156.752928
4,instance-medium-12.csv,64997,39258.452066,39040.0,8861.733708,21,16.563553,17.0,2.818288,164290.688776
5,instance-medium-13.csv,127612,92530.643753,95090.0,17901.196138,44,38.144250,41.0,9.315075,41690.410506
6,instance-medium-14.csv,137262,94658.978493,94710.0,16696.001568,44,37.815873,39.0,6.783731,88985.784985
7,instance-medium-15.csv,77225,44643.147195,44537.0,9457.819630,32,25.556710,26.0,3.239507,862738.780368
8,instance-medium-16.csv,82665,57318.910280,57477.0,14036.201364,28,23.853012,25.0,5.194537,55334.086089
9,instance-medium-17.csv,107845,80767.042931,82597.0,14515.300876,34,29.131183,31.0,6.584602,48881.136379
10,instance-medium-18.csv,133193,108318.755312,111013.0,19295.533901,47,40.928465,44.0,9.007744,47951.779928
11,instance-medium-19.csv,129589,91990.121403,91574.0,16209.348712,48,41.480595,43.0,6.889855,98364.509490
12,instance-medium-2.csv,73598,45442.139327,45280.0,10394.847568,23,17.674157,18.0,3.143659,105085.345472
13,instance-medium-20.csv,107935,78543.008820,80019.0,14165.579529,36,30.202286,31.0,5.119955,108495.138038
14,instance-medium-21.csv,55574,39776.230538,40554.0,9086.324482,21,17.106996,18.0,4.266444,38342.193879
15,instance-medium-22.csv,84719,60938.841341,62584.0,12218.698282,29,23.651852,24.0,4.137486,110315.011362
16,instance-medium-23.csv,87649,60148.941486,60771.0,11157.092902,32,26.388658,27.0,4.669993,101140.108016
17,instance-medium-24.csv,113711,86236.582605,88379.0,17837.608330,39,33.388309,36.0,7.946031,44104.704921
18,instance-medium-25.csv,66905,48771.846809,51313.0,11965.553986,23,18.616034,20.0,4.905890,41805.774383
19,instance-medium-26.csv,114655,80514.119644,81070.0,16268.021506,39,33.481973,36.0,7.569736,40944.423575
20,instance-medium-27.csv,112944,78416.437705,79717.0,16172.022047,36,30.904968,33.0,7.173839,43856.540326
21,instance-medium-28.csv,152890,107202.473488,108871.0,18739.690284,49,42.856721,46.0,9.558427,53818.921147
22,instance-medium-29.csv,87874,65548.831477,68057.0,13395.186153,30,25.236902,27.0,5.516462,49025.375000
23,instance-medium-3.csv,128224,92481.617515,95653.0,20247.016057,37,31.595801,35.0,8.254443,29620.727672
24,instance-medium-30.csv,91050,62410.103698,63283.0,11628.836777,30,25.184032,26.0,4.350193,105271.893546
25,instance-medium-31.csv,130899,98499.580012,101852.0,19779.337055,43,37.728732,40.0,8.239313,48181.417123
26,instance-medium-32.csv,119849,92135.819459,95752.0,19225.468612,48,41.783542,45.0,10.197759,33861.032838
27,instance-medium-33.csv,103594,72729.358569,73575.0,13966.057284,39,33.515426,36.0,7.387833,49782.490625
28,instance-medium-34.csv,102838,77449.012338,79985.0,14562.203847,36,31.018832,33.0,6.763953,53232.777282
29,instance-medium-35.csv,84861,53425.315576,53520.0,10983.900524,30,24.193644,25.0,3.691860,164448.788501
30,instance-medium-36.csv,96017,64866.516865,66302.0,13136.435820,38,32.733945,35.0,7.171097,54358.138770
31,instance-medium-37.csv,122574,86500.582821,87469.0,16631.214945,44,38.040562,41.0,8.247247,55758.474453
32,instance-medium-38.csv,110144,77564.745551,78399.0,16857.712502,32,27.006397,29.0,5.877749,51794.443520
33,instance-medium-39.csv,108081,76096.320728,77094.0,16285.589855,36,30.814679,33.0,6.572431,52161.475074
34,instance-medium-4.csv,57106,38960.870804,39617.0,9633.294558,20,16.137931,17.0,3.790002,49093.354140
35,instance-medium-5.csv,119428,86692.283437,87244.0,13442.178427,41,34.752678,36.0,5.827041,109438.438614
36,instance-medium-6.csv,61072,38559.257540,38116.0,9015.671783,22,17.014675,18.0,3.167874,96096.698744
37,instance-medium-7.csv,95228,65955.858243,65419.0,12589.398196,38,33.012658,35.0,7.213223,62315.774728
38,instance-medium-8.csv,69999,37322.779622,37128.0,10987.688324,21,15.603854,16.0,3.038551,107252.058111
39,instance-medium-9.csv,97456,66464.079630,66538.0,14235.115936,33,27.969697,30.0,5.985596,51209.593538

In [5]:
big = {
    "Instance": [],
    "Max users": [],
    "Average users": [],
    "Median users": [],
    "Standard deviation users": [],
    "Max sessions": [],
    "Average sessions": [],
    "Median sessions": [],
    "Standard deviation sessions": [],
    "Max duration (s)": []
}

for file in get_files("big"):
    filename = os.path.basename(file)
    big["Instance"].append(filename)
    viewer_count_array, timestamps, viewer_count_session, timestamps_sessions, sessions = calculate_stats(file)
    max_duration = max(timestamps_sessions)
    big["Max duration (s)"].append(max_duration)
    max_users = max(viewer_count_array)
    big["Max users"].append(max_users)
    big["Average users"].append(np.mean(viewer_count_array))
    big["Median users"].append(np.median(viewer_count_array))
    big["Standard deviation users"].append(np.std(viewer_count_array))
    big["Max sessions"].append(max(sessions))
    big["Average sessions"].append(np.mean(sessions))
    big["Median sessions"].append(np.median(sessions))
    big["Standard deviation sessions"].append(np.std(sessions))

big_df = pd.DataFrame(big)
display(big_df)

,Instance,Max users,Average users,Median users,Standard deviation users,Max sessions,Average sessions,Median sessions,Standard deviation sessions,Max duration (s)
0,instance-big-0.csv,220601,124304.831329,121987.0,34452.580086,31,24.220646,25.0,3.538844,1.683095e+05
1,instance-big-1.csv,140247,62221.985754,59980.0,21650.741300,18,12.310741,12.0,1.944269,9.062585e+05
2,instance-big-10.csv,109421,34442.842441,32328.0,15836.275591,11,6.214326,6.0,1.450337,8.990104e+05
3,instance-big-11.csv,128564,36643.523217,34373.0,16307.520128,12,6.912339,7.0,1.605829,1.189842e+06
4,instance-big-12.csv,180377,97129.937334,97322.0,26958.178046,23,17.997688,18.0,2.786424,1.405615e+05
5,instance-big-13.csv,192132,65648.635040,62567.0,24228.375052,20,12.646045,13.0,2.125779,9.014318e+05
6,instance-big-14.csv,250182,132656.338081,128885.0,33363.795284,34,26.400368,27.0,3.169944,3.140859e+05
7,instance-big-15.csv,85648,24125.739907,22062.0,13017.260024,8,3.862828,4.0,1.264301,8.990302e+05
8,instance-big-16.csv,228209,106538.918558,103538.0,30223.286971,27,21.115433,21.0,2.622999,3.560522e+05
9,instance-big-17.csv,144109,45796.864431,42547.0,19783.334043,15,8.474326,8.0,1.639684,1.187820e+06
10,instance-big-18.csv,148940,50170.157460,46175.0,23671.076624,16,8.400517,8.0,1.837957,6.720697e+05
11,instance-big-19.csv,90418,22894.623255,21186.0,12587.129917,7,3.861909,4.0,1.203341,9.005930e+05
12,instance-big-2.csv,157493,53166.610149,50269.0,20908.702948,16,9.974242,10.0,1.765053,9.206632e+05
13,instance-big-20.csv,94253,24501.984051,22529.0,13267.192646,8,3.807917,4.0,1.200569,1.193991e+06
14,instance-big-21.csv,169432,51790.069430,49473.0,21419.522431,13,8.743466,9.0,1.595316,3.351832e+05
15,instance-big-22.csv,142340,61442.249815,57938.0,22466.504388,17,11.022639,11.0,1.990678,3.439535e+05
16,instance-big-23.csv,110869,39188.150272,37604.0,16308.382344,12,6.996764,7.0,1.575908,6.601382e+05
17,instance-big-24.csv,167208,35221.781139,32081.0,18681.631856,12,6.022774,6.0,1.468192,1.189415e+06
18,instance-big-25.csv,238925,126639.354854,124182.0,31062.974164,33,25.621171,26.0,3.227384,3.123126e+05
19,instance-big-26.csv,187569,63543.573102,58907.0,27988.769632,16,10.367901,10.0,1.740003,3.480962e+05
20,instance-big-27.csv,110112,34201.090127,32736.0,14476.280780,10,6.100567,6.0,1.404588,9.015100e+05
21,instance-big-28.csv,121710,39584.279844,37107.0,18419.858807,11,6.497691,6.0,1.503756,9.047207e+05
22,instance-big-29.csv,106124,33842.272101,30793.0,16687.049939,11,5.624053,6.0,1.385368,1.193732e+06
23,instance-big-3.csv,220915,133537.627612,129614.0,30898.537846,34,25.648606,26.0,3.176431,2.981575e+05
24,instance-big-30.csv,167464,62869.822782,60083.0,21229.892847,18,12.855487,13.0,2.029665,3.339395e+05
25,instance-big-31.csv,121433,40903.644279,38297.0,18458.590617,12,7.300671,7.0,1.599769,9.029960e+05
26,instance-big-32.csv,201513,77340.957643,75183.0,25980.582712,21,14.347002,14.0,2.126871,6.752754e+05
27,instance-big-33.csv,135272,51300.815453,49124.0,19704.883854,18,9.742847,10.0,1.903041,9.223117e+05
28,instance-big-34.csv,181705,103371.606546,100985.0,28057.861204,25,19.870968,20.0,3.321089,1.008063e+05
29,instance-big-35.csv,163917,69325.008386,66425.0,25233.204637,18,12.853477,13.0,2.030358,3.372039e+05
30,instance-big-36.csv,81002,19725.155257,17343.0,12663.423897,6,2.892019,3.0,1.082764,1.192846e+06
31,instance-big-37.csv,199944,108502.729002,106376.0,29818.108805,29,22.047830,22.0,3.391415,1.559548e+05
32,instance-big-38.csv,272309,169832.535616,168570.0,36612.918470,40,32.883645,34.0,4.987728,1.251083e+05
33,instance-big-39.csv,174155,83252.024783,80984.0,25552.765370,19,14.263566,15.0,2.609819,1.415028e+05
34,instance-big-4.csv,163546,76792.996090,73787.0,25589.641041,21,14.719667,15.0,2.131046,6.591523e+05
35,instance-big-5.csv,217480,126284.849661,123532.0,27813.921051,31,24.338388,25.0,3.553100,1.566453e+05
36,instance-big-6.csv,130015,35398.582153,32616.0,17812.563343,10,6.157239,6.0,1.343719,9.006666e+05
37,instance-big-7.csv,182570,68691.309549,65812.0,24446.255806,20,12.746674,13.0,2.107409,9.031369e+05
38,instance-big-8.csv,178953,88595.203905,86267.0,25687.519332,23,16.946628,17.0,2.422299,3.768771e+05
39,instance-big-9.csv,119633,25886.691279,23018.0,15314.927421,8,3.784158,4.0,1.188065,1.204502e+06

In [6]:
small_df.to_csv("instances_small.csv", index=False)
medium_df.to_csv("instances_medium.csv", index=False)
big_df.to_csv("instances_big.csv", index=False)

In [12]:
# aggregate dataframes for small, medium, and big instances separately
small_df = pd.read_csv("instances_small.csv")
medium_df = pd.read_csv("instances_medium.csv")
big_df = pd.read_csv("instances_big.csv")
small_df = small_df.drop(columns=["Instance"])
small_df_mean = small_df.mean()

medium_df = medium_df.drop(columns=["Instance"])
medium_df_mean = medium_df.mean()
big_df = big_df.drop(columns=["Instance"])
big_df_mean = big_df.mean()

data = {
    "Small": small_df_mean,
    "Medium": medium_df_mean,
    "Big": big_df_mean
}
summary_df = pd.DataFrame(data).T
# Add "Average of " to each column name
summary_df.columns = [f"Average of {col}" for col in summary_df.columns]
display(summary_df)
summary_df.to_csv("instances_summary.csv", index=True)

,Average of Max users,Average of Average users,Average of Median users,Average of Standard deviation users,Average of Max sessions,Average of Average sessions,Average of Median sessions,Average of Standard deviation sessions,Average of Max duration (s)
Small,9575.600,5144.700451,5141.975,1839.435565,6.625,4.178748,4.350,1.420382,65761.897084
Medium,99994.650,70607.397428,71711.000,14083.133633,34.575,29.252445,30.925,6.078160,90271.838483
Big,160917.725,67682.684292,65114.625,22616.050531,18.350,12.664881,12.775,2.126278,655646.542732

In [ ]:
def plot_instance(file, figtitle):
    viewer_count_array = []
    viewer_count = 0
    viewer_count_session = {}
    timestamps = []
    timestamps_sessions = [0]
    sessions = [0]

    with open(file, 'r') as f:
        # Skip header line
        next(f)
        for line in f:
            parts = line.strip().split(',')
            if len(parts) < 4:
                continue

            repeat = int(parts[1])
            event = int(parts[2])
            timestamp = float(parts[3])
            id_val = parts[0]

            if event == 0:  # Session start
                session = f"{id_val}-{repeat}"
                viewer_count_session[session] = {
                    "viewer_count": 0,
                    "viewer_count_array": [0],
                    "timestamps": [timestamp]
                }
                sessions.append(sessions[-1] + 1)
                timestamps_sessions.append(timestamp)

            elif event == 2:  # Session end
                session = f"{id_val}-{repeat}"
                if session in viewer_count_session:
                    viewer_count -= viewer_count_session[session]["viewer_count"]
                sessions.append(sessions[-1] - 1)
                timestamps_sessions.append(timestamp)

            elif event in [1, 3]:  # User join/leave
                session = f"{'-'.join(id_val.split('-')[:-1])}-{repeat}"
                if session in viewer_count_session:
                    session_data = viewer_count_session[session]
                    
                    if event == 1:  # User join
                        session_data["viewer_count"] += 1
                        viewer_count += 1
                    else:  # User leave
                        session_data["viewer_count"] -= 1
                        viewer_count -= 1

                    session_data["viewer_count_array"].append(session_data["viewer_count"])
                    session_data["timestamps"].append(timestamp)

            viewer_count_array.append(viewer_count)
            timestamps.append(timestamp)

        viewer_count_array.append(viewer_count)
        timestamps.append(timestamp)
    fig, ax = plt.subplots(figsize=(15, 7))
    ax.plot(timestamps, viewer_count_array, 'b--', label="Total viewers")
    for session in viewer_count_session:
        session_label = '-'.join(session.split("-")[:-2])
        ax.plot(viewer_count_session[session]["timestamps"], viewer_count_session[session]["viewer_count_array"])
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("Number of viewers")
    # ax.set_xticks(range(0, int(max(timestamps)) + 1, 1000))
    ax.set_xticklabels(ax.get_xticks(), rotation=45)
    ax2 = ax.twinx()
    ax2.plot(timestamps_sessions, sessions, 'r--', label="Total sessions")
    ax2.set_ylabel("Number of sessions")
    fig.legend()
    ax.grid()
    ax2.grid()
    fig.suptitle(figtitle)

In [ ]:
plot_instance('instances/instances-big/instance-big-1.csv', "Big instance viewer progression")