In [10]:
import pandas as pd
import os

In [11]:
simulated_dir = 'simulated/'
algorithm_map = {
    "base": "A",
    "link": "B",
}
link_progression = [1, 2, 3, 5, 10, 20]
max_connections = 500

In [14]:
# read all csvs in simulated directory and save as dataframes
simulated_files = os.listdir(simulated_dir)
simulated_files = [simulated_dir + file for file in simulated_files]
simulated_data = []
link_dfs = 0
for file in simulated_files:
    file_name = file.split('/')[-1]
    algorithm = algorithm_map[file_name.split('-')[0]]
    df = pd.read_csv(file)
    simulated_data_value = {
        'algorithm': algorithm,
        'max_connections': max_connections,
        'df': df,
    }
    if algorithm == 'B':
        link_p = link_progression[link_dfs]
        link_dfs += 1
        simulated_data_value['B_max_reservations'] = int(link_p)
    simulated_data.append(simulated_data_value)
simulated_data = pd.DataFrame(simulated_data)

In [22]:
final_values = []

for i in range(len(simulated_data)):
    data = simulated_data.iloc[i]
    algorithm = data['algorithm']
    max_connections = data['max_connections']
    df = data['df']
    if algorithm == 'B':
        max_reservations = data['B_max_reservations']

    final_value = {
        "Algorithm": algorithm,
        "Maximum connections per server": max_connections,
        "Maximum connections reserved for linked servers": max_reservations if algorithm == 'B' else None,
        "Final Server Time Cost (hours of server usage)": round(df['server_platform_time_cost'].max() / 3600, 3),
    }
    final_values.append(final_value)

final_values_df = pd.DataFrame(final_values)
final_values_df_sorted = final_values_df.sort_values(by="Final Server Time Cost (hours of server usage)", ascending=True).reset_index(drop=True)
display(final_values_df)
display(final_values_df_sorted)

,Algorithm,Maximum connections per server,Maximum connections reserved for linked servers,Final Server Time Cost (hours of server usage)
0,A,500,NaN,406.226
1,B,500,1.0,308.705
2,B,500,2.0,296.894
3,B,500,3.0,290.059
4,B,500,5.0,282.024
5,B,500,10.0,286.101
6,B,500,20.0,288.630

,Algorithm,Maximum connections per server,Maximum connections reserved for linked servers,Final Server Time Cost (hours of server usage)
0,B,500,5.0,282.024
1,B,500,10.0,286.101
2,B,500,20.0,288.630
3,B,500,3.0,290.059
4,B,500,2.0,296.894
5,B,500,1.0,308.705
6,A,500,NaN,406.226