In [2]:
import pandas as pd
import os

In [1]:
simulated_dir = 'simulated/'
algorithm_map = {
    "base": "A",
    "link": "B",
    "full": "C"
}

In [3]:
# read all csvs in simulated directory and save as dataframes
simulated_files = os.listdir(simulated_dir)
simulated_files = [simulated_dir + file for file in simulated_files]
simulated_data = []
link_dfs = 0
for file in simulated_files:
    file_name = file.split('/')[-1]
    file_name_split = file_name.split('.')[0].split('-')
    algorithm = algorithm_map[file_name_split[0]]
    run = file_name_split[-1]
    df = pd.read_csv(file)
    simulated_data_value = {
        'algorithm': algorithm,
        'max_connections': max_connections,
        'df': df,
    }
    if algorithm == 'A':
        if run == '0':
            simulated_data_value['Sort viewers by'] = "Higher load"
        elif run == '1':
            simulated_data_value['Sort viewers by'] = "Lower load"
        elif run == '2':
            simulated_data_value['Sort viewers by'] = "Round Robin"
        elif run == 'r':
            simulated_data_value['Sort viewers by'] = "Random"
    elif algorithm == 'B':
        link_p = link_progression[link_dfs]
        link_dfs += 1
        simulated_data_value['B_max_reservations'] = int(link_p)
        simulated_data_value['Sort viewers by'] = "Higher load"
    simulated_data.append(simulated_data_value)
simulated_data = pd.DataFrame(simulated_data)

In [4]:
final_values = []

for i in range(len(simulated_data)):
    data = simulated_data.iloc[i]
    algorithm = data['algorithm']
    max_connections = data['max_connections']
    df = data['df']
    sorted_by = data['Sort viewers by']
    if algorithm == 'B':
        max_reservations = data['B_max_reservations']

    final_value = {
        "Algorithm": algorithm,
        "Maximum connections per server": max_connections,
        "Sort viewers by": sorted_by,
        "Maximum connections reserved for linked servers": max_reservations if algorithm == 'B' else None,
        "Final Server Time Cost (hours of server usage)": round(df['server_platform_time_cost'].max() / 3600, 3),
    }
    final_values.append(final_value)

final_values_df = pd.DataFrame(final_values)
final_values_df_sorted = final_values_df.sort_values(by="Final Server Time Cost (hours of server usage)", ascending=True).reset_index(drop=True)
display(final_values_df)
display(final_values_df_sorted)

,Algorithm,Maximum connections per server,Sort viewers by,Maximum connections reserved for linked servers,Final Server Time Cost (hours of server usage)
0,A,500,Higher load,NaN,406.226
1,A,500,Lower load,NaN,406.226
2,A,500,Round Robin,NaN,405.788
3,A,500,Random,NaN,404.595
4,B,500,Higher load,1.0,308.705
5,B,500,Higher load,2.0,296.053
6,B,500,Higher load,3.0,289.702
7,B,500,Higher load,5.0,282.024
8,B,500,Higher load,10.0,286.101
9,B,500,Higher load,20.0,288.630

,Algorithm,Maximum connections per server,Sort viewers by,Maximum connections reserved for linked servers,Final Server Time Cost (hours of server usage)
0,B,500,Higher load,5.0,282.024
1,B,500,Higher load,10.0,286.101
2,B,500,Higher load,20.0,288.630
3,B,500,Higher load,3.0,289.702
4,B,500,Higher load,2.0,296.053
5,B,500,Higher load,1.0,308.705
6,A,500,Random,NaN,404.595
7,A,500,Round Robin,NaN,405.788
8,A,500,Higher load,NaN,406.226
9,A,500,Lower load,NaN,406.226